###signup
POST http://localhost:3305/v1/api/user/signup
Content-Type: application/json
x-api-key: 9aaf87085dcbbdd4241c2661346c2bac5340e3a5a6e65e945ced3535ca1d9586ebfd9f44625adee493c41178de30d0c88b8727fcadb4a17ab2dff08e9a4dc97e

{
    "name": "Sonic Chan",
    "email": "chan.sonic9@gmail.com",
    "password": "abc123"
}

###login
POST http://localhost:3305/v1/api/user/login
Content-Type: application/json
x-api-key: 9aaf87085dcbbdd4241c2661346c2bac5340e3a5a6e65e945ced3535ca1d9586ebfd9f44625adee493c41178de30d0c88b8727fcadb4a17ab2dff08e9a4dc97e

{
    "email": "chan.sonic9@gmail.com",
    "password": "abc123"
}

###logout
POST http://localhost:3305/v1/api/user/logout
Content-Type: application/json
x-api-key: 9aaf87085dcbbdd4241c2661346c2bac5340e3a5a6e65e945ced3535ca1d9586ebfd9f44625adee493c41178de30d0c88b8727fcadb4a17ab2dff08e9a4dc97e
x-user-id: 66024f724bca3a44ebe951ca
authorization: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjAzZGE5Y2Q2YWZiMmRiNDcyZmUwNzkiLCJlbWFpbCI6ImNoYW4uc29uaWM3QGdtYWlsLmNvbSIsImlhdCI6MTcxMTUyODY0NSwiZXhwIjoxNzEyMTMzNDQ1fQ.NiT6mqLxw01VzYaymuPzYYl2a1Ohbs8y5YnUJD9V24b0v6rVYoPMkcPCH1yE6n9_JUpN8Bt6fdmEb-5P4yLtQrwiG_otKjG06Pknquh0KFeQUI6jMBVgbzwgwxZ80uR5LGWc3zLhMvLFtBkJ8otDynjmWvWgD9mPxbI9WEbdZOZuKeuNVaRbZ-lGI14gafAFXuhEiu9EAE04dPRcYYxMr7VgWkQZAGUX-DEb9Q91wK6T2TSPoeDjkSP_NcU3oUG9tcwaYt1UDPSDZ3qV5ZWJwZsj2SihrQJXjXQtdZSUv-RtWVf3sHH59trNAXNne7_0UItuT35GbHnaLdK3jukTcW4g0FmOhJqkZyQ47thwng8rFqAIvKEF-mToT2U-puJVQMY_KrIKw9bWZkwkybP7d4UUFNe-brQMJ0-ytSOdqMPNVpURubXvt8cUKkHSfFuYJu2N2XZWln8P6NT2nsVWMmiqth9ZuIk_Kp90fj-mllJ3Xd1Z4TqSf973slBUon24EJkY2eQyoeAVvTbmTWJ4GTL6IYDrcUqakPrg5WdI4TKCCakNoseNk3vFMo7lGjGUqVwHglsCdiEs8Ta2v00Y-N4doI8AchXkkE7-YytEgU0hF_ha2UMZqtzmFHudQkZ4lO-60odbGCnuPxyMAvUgNaMZCSfsVNABz2swlIIbwvU

{

}

###CheckRefreshToken
POST http://localhost:3305/v1/api/user/checkrefreshtoken
Content-Type: application/json
x-api-key: 9aaf87085dcbbdd4241c2661346c2bac5340e3a5a6e65e945ced3535ca1d9586ebfd9f44625adee493c41178de30d0c88b8727fcadb4a17ab2dff08e9a4dc97e
x-user-id: 6603dfea63377b4435ef21d2
authorization: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjAzZGZlYTYzMzc3YjQ0MzVlZjIxZDIiLCJlbWFpbCI6ImNoYW4uc29uaWM5QGdtYWlsLmNvbSIsImlhdCI6MTcxMTUzMDAwMywiZXhwIjoxNzEyMTM0ODAzfQ.lc-gu8h2QnKKrbfLeUTzKlQ0Hi6Ddwu6IgfoS3mb1Z6IqH5RUGYVylbgDXr_UJ9NJg4vWpzQpUAhrJYZxo83m22YywARAId4G5dSKb-RV8qSlce1wGh21tYk6YYUAG25QNzU6QwMoJh2k1UGHqjvBdwa0F_jweeSE9B-WP0vxznAKGrBWiDIxHk66Tbw4ViQaNsJZvObMkZvsKuVEgL_a2mVJmj9FTz0WcunduM-e14Fx7dKzlM69GVJlrGEw317m5uAyMnTJZ3evcHbYZ_UqWQM038jbk2s4K1fOno-N49xLlJpt5i85_e549by9ndz5um5Pc9AG6nra-_5Lg2gW6-OhRZOGE3zQRrGv9H23-AWWdtd9LW80NBzEEZaXM6LgcPUo4ij_pLXh--8LUzcOlpr_kXQTpPydIsjWoBOkw38b0p-5ZQC7eAhDq3Nw2r3O9G4vtireLs3X7B7qbO4W5U8K72mEVVy_MHO8QP3_Q7iWQ-KaTZil7misYRSbesEk4MfyO-AjhZ2SBLlnmSujfpKvzVdRTIdgEtz-0aF-YXPibnjJkhGvI77e2VIOCpD7CabPNay4Wq9FSf-qnlTAG0VKglhzlOE8MvlSzHzjJy35XCt38U7IZLL8sCgI32VJaT06Hx20j3fbUBww-zdKI3vP81liYJpisCFTJ_OwEA

{
    "refreshToken":  "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjAzZGZlYTYzMzc3YjQ0MzVlZjIxZDIiLCJlbWFpbCI6ImNoYW4uc29uaWM5QGdtYWlsLmNvbSIsImlhdCI6MTcxMTUzMDAwMywiZXhwIjoxNzEyMTM0ODAzfQ.lc-gu8h2QnKKrbfLeUTzKlQ0Hi6Ddwu6IgfoS3mb1Z6IqH5RUGYVylbgDXr_UJ9NJg4vWpzQpUAhrJYZxo83m22YywARAId4G5dSKb-RV8qSlce1wGh21tYk6YYUAG25QNzU6QwMoJh2k1UGHqjvBdwa0F_jweeSE9B-WP0vxznAKGrBWiDIxHk66Tbw4ViQaNsJZvObMkZvsKuVEgL_a2mVJmj9FTz0WcunduM-e14Fx7dKzlM69GVJlrGEw317m5uAyMnTJZ3evcHbYZ_UqWQM038jbk2s4K1fOno-N49xLlJpt5i85_e549by9ndz5um5Pc9AG6nra-_5Lg2gW6-OhRZOGE3zQRrGv9H23-AWWdtd9LW80NBzEEZaXM6LgcPUo4ij_pLXh--8LUzcOlpr_kXQTpPydIsjWoBOkw38b0p-5ZQC7eAhDq3Nw2r3O9G4vtireLs3X7B7qbO4W5U8K72mEVVy_MHO8QP3_Q7iWQ-KaTZil7misYRSbesEk4MfyO-AjhZ2SBLlnmSujfpKvzVdRTIdgEtz-0aF-YXPibnjJkhGvI77e2VIOCpD7CabPNay4Wq9FSf-qnlTAG0VKglhzlOE8MvlSzHzjJy35XCt38U7IZLL8sCgI32VJaT06Hx20j3fbUBww-zdKI3vP81liYJpisCFTJ_OwEA"
}