###signup
POST http://localhost:3305/v1/api/user/signup
Content-Type: application/json
x-api-key: 9aaf87085dcbbdd4241c2661346c2bac5340e3a5a6e65e945ced3535ca1d9586ebfd9f44625adee493c41178de30d0c88b8727fcadb4a17ab2dff08e9a4dc97e

{
    "name": "Sonic Chan",
    "email": "chan.sonic3@gmail.com",
    "password": "abc123"
}

###login
POST http://localhost:3305/v1/api/user/login
Content-Type: application/json
x-api-key: 9aaf87085dcbbdd4241c2661346c2bac5340e3a5a6e65e945ced3535ca1d9586ebfd9f44625adee493c41178de30d0c88b8727fcadb4a17ab2dff08e9a4dc97e

{
    "email": "chan.sonic3@gmail.com",
    "password": "abc123"
}

###logout
POST http://localhost:3305/v1/api/user/logout
Content-Type: application/json
x-api-key: 9aaf87085dcbbdd4241c2661346c2bac5340e3a5a6e65e945ced3535ca1d9586ebfd9f44625adee493c41178de30d0c88b8727fcadb4a17ab2dff08e9a4dc97e
x-user-id: 66024f724bca3a44ebe951ca
authorization: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjAyNGY3MjRiY2EzYTQ0ZWJlOTUxY2EiLCJlbWFpbCI6ImNoYW4uc29uaWMzQGdtYWlsLmNvbSIsImlhdCI6MTcxMTQ0ODAzMiwiZXhwIjoxNzEyMDUyODMyfQ.B3CmzYlHSa5Yj0hSeOM-nKypooLxXfueElrYDE35csiZjGb88synKfucTwg-edYus4LwdqvwLgByLyilkYKxTDu4Cpg9J7xVw0M2_6I-lVDLvbaJTLwFNOJFK54R5fNn6VQ40OfBBe0CxXYvkMW6ZCOg_VDaaiPyWgsqQnZTme86FzysujS4wEqVTCEPUd7qqlizD21A3Sh1sY53KsAgME-jKXBo3yY_Zxz6bvTEcTZx8JmSCmSp-Zttdsofnhn4eJogAbA0ltNwwYyHPtpNyxhdyY956hImpTNkCIkMfzsGzQsa1FaMK1rqcXsFFAKMWM2fHO7xS9E3ioA3eQ5wWAuFBn5jCUMz6MTPVctYimJa0PDzsOK44lwE5QL4IMGpPDnSyFceHCcKqf5r0Xi5lT9S6qxGOEnxcSVOGGNaalfwD6Abud4EKcKIv91u24lvTsVu7WbVSjL_XlwmISZqVuaIMfRArSZeYWwGSqnJllHH6CZwk3pVu20xVYnneZ_hmsGHPF2oOpqmCw6ko0U2mdJd8icMeJ4ijMGBjolrO0Q20y0BP9USWOvn13Wthmogav4fGilJvLLqh6JxjfN5JUwvrEDd0D6PSmBNgoxtJgpln5JeCjA2BlEdMEx_sWipguDgLCsX6LHhRdkG1Q4vDo1KBCuS9YRmdGsfyTPnG8Q

{

}