###logout
POST http://localhost:3305/v1/api/product/
Content-Type: application/json
x-user-id: 660b8ba89244b16dabe7fb86
authorization: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjBiOGJhODkyNDRiMTZkYWJlN2ZiODYiLCJlbWFpbCI6ImNoYW4uc29uaWM5QGdtYWlsLmNvbSIsImlhdCI6MTcxMjY0OTc3NCwiZXhwIjoxNzEzMjU0NTc0fQ.fUaByR3JLX52ekq0mz1a_aDpNWkHyPjMboq8600xVZG2mclVOjR6Ao9Pp7dDP_ZNWrYTYrGLeZ3PHPb4n_M-_BLVaUKgV6OICoUmxqobdZSLxg2JXKGQc7h2VGj5ntOuJ-hp44akWLieaWwbRQ6Q5U-gZhI3Zk_lgXuWQqxAvk0eQEosmf9takJLsphrRxxazSPoy3_HL-WQC76US1YkyyOJDRnVP77_GmiiHKZZsDv7H1Nhv-l5cbtZ44xxK7kTRVcjvLx8V8CQcTlJyeutXn6JPjX6-99A0amHkLFZLPFLPnIzdrFcvlOcOUIfXqDmuksmeNthnuVT0zWOzKIy3GJQuYpMZFX567FANvlnQ-FBhbHfTiTwxvyuW0oh1nIfUGItz5r1sLx_R96PXO33p61ppObkYegJSRY-UNd_KJdtTp0cSHE87ZU0e0pIWisWEr8E66m4wbAkG7tRlw5C77I5BCjDeXtGuN9slT_ROju9twG3WS7G5QvtgIh4xDZ36Si1FcMkMPS-m0pua4P_XV-urT0SCe7FyrGYtZVz7UV95vKydY0PGks2erogAdiCd4150aF5DkYo17t6BSqcIz9kxuELbMX-dSplYj6o9GKGOyGBaQQ5aa_SCJlEUG35d-PLBiCptLGdmZV06RNfuju-SpZVKo6R9MTr7H4ofoQ

{

}